#!/usr/bin/env bash
# Copyright (C) 2026 Fiber
#
# All rights reserved. This script, including its code and logic, is the
# exclusive property of Fiber. Redistribution, reproduction,
# or modification of any part of this script is strictly prohibited
# without prior written permission from Fiber.
#
# Conditions of use:
# - The code may not be copied, duplicated, or used, in whole or in part,
#   for any purpose without explicit authorization.
# - Redistribution of this code, with or without modification, is not
#   permitted unless expressly agreed upon by Fiber.
# - The name "Fiber" and any associated branding, logos, or
#   trademarks may not be used to endorse or promote derived products
#   or services without prior written approval.
#
# Disclaimer:
# THIS SCRIPT AND ITS CODE ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. IN NO EVENT SHALL
# FIBER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF USE,
# DATA, PROFITS, OR BUSINESS INTERRUPTION) ARISING OUT OF OR RELATED TO THE USE
# OR INABILITY TO USE THIS SCRIPT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Unauthorized copying or reproduction of this script, in whole or in part,
# is a violation of applicable intellectual property laws and will result
# in legal action.

set -euo pipefail

EXTENSIONS="ts tsx js mjs cjs jsx dart go c h cpp hpp cc rs java kt swift proto php py sh rb sql"
EXCLUDED="node_modules .git .dart_tool __pycache__"
SCAN_LINES=60

COPYRIGHT="Copyright (C) 2026 Fiber"
LICENSE_NAME="All rights reserved"
GENERATED="auto-generated|@generated|DO NOT EDIT|Generated by the protocol buffer compiler|generated file - do not edit"

find_arguments=()
for extension in $EXTENSIONS; do
  find_arguments+=(-o -name "*.$extension")
done
unset 'find_arguments[0]'

prune_arguments=()
for directory in $EXCLUDED; do
  prune_arguments+=(-name "$directory" -o)
done

listing=$(mktemp)
trap 'rm -f "$listing"' EXIT

find . \( "${prune_arguments[@]}" -false \) -prune -o -type f \( "${find_arguments[@]}" \) -print \
  | grep -v -E '\.(g|pb|pbenum|pbjson|pbserver)\.dart$' \
  | grep -v -E '_pb\.ts$' \
  | sort > "$listing"

if [ ! -s "$listing" ]; then
  echo "No source file to check"
  exit 0
fi

report=$(awk -v scan="$SCAN_LINES" -v copyright="$COPYRIGHT" -v license="$LICENSE_NAME" -v generated="$GENERATED" '
  NR == FNR { all[++total] = $0; next }
  FNR == 1 { inHeader[FILENAME] = 1 }
  {
    if (!(FILENAME in inHeader)) next
    if (FNR > scan) { delete inHeader[FILENAME]; next }
    if (FNR > 1 && $0 !~ /^(\/\/|#|--)/) { delete inHeader[FILENAME]; next }
    if (FNR == 1 && $0 !~ /^(#!|\/\/|#|--)/) { delete inHeader[FILENAME]; next }
    if (index($0, copyright)) hasCopyright[FILENAME] = 1
    if (index($0, license)) hasLicense[FILENAME] = 1
    if ($0 ~ generated) isGenerated[FILENAME] = 1
  }
  END {
    missing = 0; checked = 0; skipped = 0
    for (i = 1; i <= total; i++) {
      file = all[i]
      if (file in isGenerated) { skipped++; continue }
      checked++
      if (!(file in hasCopyright)) { print "MISSING  " file; missing++; continue }
      if (!(file in hasLicense)) {
        print "STALE    " file
        print "         has a copyright line but does not name the license"
        missing++
      }
    }
    print "@" missing "\t" checked "\t" skipped
  }
' "$listing" $(cat "$listing"))

summary=$(printf '%s\n' "$report" | grep '^@' | tail -1)
printf '%s\n' "$report" | grep -v '^@' || true

missing=$(printf '%s' "$summary" | cut -f1 | tr -d '@')
checked=$(printf '%s' "$summary" | cut -f2)
skipped=$(printf '%s' "$summary" | cut -f3)

if [ "$missing" -gt 0 ]; then
  cat >&2 <<EOF

$missing of $checked source files are missing the license header.

Every source file carries the proprietary Fiber header, in the comment syntax
of its language: // for TypeScript, Dart, Go, C and friends, # for shell,
Python and Ruby, -- for SQL. Copy it from a neighbouring file of the same
language.

This repository is private and its source is not distributed. Only the binaries
it builds for scribe and docs are published, under the licence that governs the
scribe repository. Do not put that licence in this source.

The header goes at the very top, except in a file that starts with a shebang,
where it goes on the line after it.
EOF
  exit 1
fi

echo ""
echo "Checked $checked source files, all carry the license header"
echo "Skipped $skipped generated files"
